spring:
#  datasource:
##    url: jdbc:h2:mem:testdb
##    driver-class-name: org.h2.Driver
##    username: sa
##    password: ""
#    url: jdbc:mysql://localhost:3306/twitterdb
#    username: dev
#    password: dev123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace